server:
  port: 9990

mysql:
  host: 110.41.128.19
  port: 3306
  user: root
  password: 
  db: pandemo

redis:
  addr: 
  password: 
  db: 0
  # 登陆 Token过期时间 单位 小时
  tokenTime: 1
  # 验证码过期时间 单位 分钟
  emailTime: 5
JWT:
  secret_key: stephen-demo
  Issuer: stephen-demo-NB

emailCode:
  seedEmail: 
  mailPassword: 
  seedSubject: 验证码发送测试
  eFrom: 验证码测试 <w2477284535@163.com>
  addr: smtp.163.com:465
  host: smtp.163.com
  Server: smtp.163.com
