server:
  port: 9990

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 11223344
  db: panDemo

redis:
  addr: 127.0.0.1:6379
  password:
  db: 2
  tokenTime: 10
  emailTime: 5

jwt:
  tokenExpire: 10