# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Backend Demo CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20.2'

      - name: Install dependencies
        run: go mod download

      - name: Build and test
        run: |
          go build -o app
          go test -v -race ./...

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: your-registry/your-image:latest

      - name: Deploy to Kubernetes
        uses: appleboy/kubectl-action@v1.2.0
        with:
          args: apply -f kubernetes/deployment.yaml
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
